### ISSUE TITLE
run Tick later

### ISSUE THREAD

**Issue by PedroMPagani** [CorneliusMa/SilkSpawners_v2#12]
What's the reason of running the set spawner type 5 ticks after only? why not make it 1t or 2t

**Comment by CorneliusMa** [comment]
I have changed it. Thanks.

**Comment by PedroMPagani** [comment]
Hey Cornelius, I am sorry for the long response, I completely lost this, I just tried and lgtm awesome! Good job

**Comment by PedroMPagani** [comment]
This has actually fixed one issue we were had and I just thought about it, players were saying that their iron golem spawners were becoming PIGS all the time, and that's actually to me what it seems to be a tick issue, where he would be able to place the spawner and break it really fast at the same time, before the spawner even got set to the mob type.

Sounds like possible? woudln't happen for high latnecy players but most of our network holds players with < 50ms
