### ISSUE TITLE
/ss commands

### ISSUE THREAD

**Issue by aytexii** [CorneliusMa/SilkSpawners_v2#13]
Hello, I updated my SilkSpawners plugin to 2.1.5 after updating my server to 1.19. However, I am having an issue with the plugin because of this version change. The aliased commands under "/ss" do not work anymore. In fact, my players are now unable to even change the spawner type because of this. Here is a screenshot of the only commands that work with this plugin now. https://prnt.sc/Q2s60U4V1Wie

**Comment by CorneliusMa** [comment]
I have never tested the plugin with command aliases, but if there is a bug, I will fix it with the next update.
