### ISSUE TITLE
Axolotl and Vex (perhaps even more) not spawning.

### ISSUE THREAD

**Issue by Luka27Svedalia** [CorneliusMa/SilkSpawners_v2#14]
Greetings, I seem to have faced an issue as to where Axolotls and Vex wont spawn from the mob-spawners.
Striders and Wardens still work however, so it can't be a version issue?

**Comment by CorneliusMa** [comment]
Hi. This seems to be a bug with some entities. I will fix it asap.

**Comment by CorneliusMa** [comment]
Looks like some mobs can't spawn naturally (see: https://minecraft.fandom.com/wiki/Vex), so unfortunately this is not fixable
