### ISSUE TITLE
Permissions do nothing

### ISSUE THREAD

**Issue by jango-bob** [CorneliusMa/SilkSpawners_v2#16]
Adding permissions with groupmanager has done nothing, nobody can place anything or get a spawner back.

**Comment by CorneliusMa** [comment]
Hello, permissions work for me. Can you tell me what permissions you have set?

**Comment by jango-bob** [comment]
I have every single one enabled on groupmanagerx and set the rank to
default. They only work then you’re a server op

**Comment by CorneliusMa** [comment]
This was a problem caused by GroupManager. Its fixed now
