### ISSUE TITLE
Missing Permissions

### ISSUE THREAD

**Issue by dhumbert8** [CorneliusMa/SilkSpawners_v2#21]
I'm unsure if there was an error with the install, some people made comments as if it were obvious and others seemed to have a similar issue as me: where can I edit permissions so that non-op players can break and receive spawners? Currently an operator can use silk touch on a spawner and get it back, but if they are de-op'd, and just a player they only get the experience as they normally would.

My config file currently looks like this. Do I add lines for permissions, is this file wrong, or is there a different file I should be looking at?
![image](https://user-images.githubusercontent.com/24499675/191373268-e2590c40-9930-4c36-87f6-1531c4f15ba0.png)

**Comment by CorneliusMa** [comment]
You need a permission Plugin or something to set the permissions.

**Comment by TomSnoei** [comment]
I have the same problem but I actually use a perms plugin. I set the permissions to break and place spawners and still only people with OP can break them

**Comment by CorneliusMa** [comment]
> I have the same problem but I actually use a perms plugin. I set the permissions to break and place spawners and still only people with OP can break them

Hello, can you please tell me what permissions you have set exactly?

**Comment by TomSnoei** [comment]
I managed to fix the perms already. I used silkspawners.break instead of silkspawners.break.*. So i forgot to add the ".*". It all works now
