### ISSUE TITLE
Permissions are not working as intended.

### ISSUE THREAD

**Issue by SaumyaKhobragade** [CorneliusMa/SilkSpawners_v2#46]
![image](https://github.com/CorneliusMa/SilkSpawners_v2/assets/78600365/c6b8d632-0220-42a3-a712-41eb29911295)
![image](https://github.com/CorneliusMa/SilkSpawners_v2/assets/78600365/b46bbe0b-76c4-4526-b076-6ebce85bc7c3)
![image](https://github.com/CorneliusMa/SilkSpawners_v2/assets/78600365/8b0aeb46-1d7c-4993-bbbd-0eca7295959b)

**Comment by Gertius** [comment]
By default, users need the `silkspawners.command.set` permission to use the set command at all.

Once granted, this also gives them the `silkspawners.command.set.*` permission by default, which grants them the ability to set all entity types.

**So to fix your issue, you need to:**
1. Grant the `silkspawners.command.set` permission
    - In LuckPerms: `/lp group default permission set silkspawners.command.set true`
2. Ungrant the `silkspawners.command.set` permission
    - In LuckPerms: `/lp group default permission set silkspawners.command.set.* false`
    - In most other permission plugins, give them the permission: `-silkspawners.command.set.*`
3. Grant each `silkspawners.command.set.<entity_type>` permission as needed

**Comment by SaumyaKhobragade** [comment]
thanks a lot
